#!/bin/sh
#
# Servidor basico Debian / Version para Xen
#
# Jesus Lara
# --
# http://www.devel.com.ve/
#

# define prefix
prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/lib/xen-tools/common.sh ]; then
    . /usr/lib/xen-tools/common.sh
else
    echo "Installation problem"
fi

########################################
#
# configure apt
# 

mirror="http://172.16.30.1/mirrors/debian/"
dist=`xt-guess-suite-and-mirror --suite`

# disable apt sources.list base
sed -i 's/^deb/#deb/' ${prefix}/etc/apt/sources.list

# erase all .list repositories
rm -f ${prefix}/etc/apt/sources.list.d/*.list
/bin/echo 'Acquire::Check-Valid-Until "false";' > ${prefix}/etc/apt/apt.conf.d/80update

#
# create local apt list
#
# oficial repositories
cat <<E_O_APT > ${prefix}/etc/apt/sources.list.d/local.list
# oficial
deb ${mirror} ${dist} main contrib non-free
E_O_APT

# backport repositories
cat <<E_O_APT > ${prefix}/etc/apt/sources.list.d/backports.list
deb ${mirror} ${dist}-backports main contrib non-free
E_O_APT

#
#  Update APT lists.
#
chroot ${prefix} /usr/bin/apt-get update


#
#  Install some new packages - do this first to avoid dependency errors.
#
installDebianPackage ${prefix} rsyslog
installDebianPackage ${prefix} deborphan
installDebianPackage ${prefix} less
installDebianPackage ${prefix} screen


# Remove unwanted packages
removeDebianPackage ${prefix} tasksel tasksel-data
removeDebianPackage ${prefix} pciutils
removeDebianPackage ${prefix} fdutils


